---
# roles/omv/handlers/main.yml

- name: Reboot if cmdline changed
  ansible.builtin.reboot:
    msg: "Rebooting to apply cgroup settings"
    reboot_timeout: 300

- name: Restart openmediavault-engined
  ansible.builtin.systemd:
    name: openmediavault-engined
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
